# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: ArchiveFiles@2
  displayName: Build
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
  displayName: publish artifacts

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'service_connection_html_app'
    appType: 'webApp'
    WebAppName: 'html-poc-app02'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
